# receber um dado, informar seu tipo primitivo e realizar as verificações

x = input('Digite algo: ')
print(type(x))
print(x.isnumeric())
print(x.isalpha())
print(x.isalnum())
print(x.isupper())
print(x.islower())
print(x.printable())
print(x.isascii())
print(x.isdecimal())
print(x.isdigit())
print(x.isindentifier())
print(x.isspace())
print(x.istitle())
